// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwq5NGC0pLy5AjAsxKz1gV012pPxQosC0',
    appId: '1:143995583308:android:ab93f0f1b10bb7f3e22de9',
    messagingSenderId: '143995583308',
    projectId: 'practiceproject-14584',
    storageBucket: 'practiceproject-14584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELo7Krys6dvcS-DXn8eWaZdgEmidgDaA',
    appId: '1:143995583308:ios:748f92a3f5c7b048e22de9',
    messagingSenderId: '143995583308',
    projectId: 'practiceproject-14584',
    storageBucket: 'practiceproject-14584.firebasestorage.app',
    iosBundleId: 'com.example.practiceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUF6svLLEMV2wlUACEPHHYT_qT3nprAk',
    appId: '1:143995583308:web:cc7572c61477212de22de9',
    messagingSenderId: '143995583308',
    projectId: 'practiceproject-14584',
    authDomain: 'practiceproject-14584.firebaseapp.com',
    storageBucket: 'practiceproject-14584.firebasestorage.app',
    measurementId: 'G-KYJ9B8D6H8',
  );
}
