# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta_old do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :beta do
    sh("flutter build apk")
    firebase_app_distribution(
      app:"1:143995583308:android:ab93f0f1b10bb7f3e22de9",
      firebase_cli_token:ENV["FIREBASE_TOKEN"],
      service_credentials_file:"C://Users//mihal//Documents//GitHub//practice_project//practiceproject-14584-firebase-adminsdk-fbsvc-d1496e0645.json",
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
    )
  end
end
